-- SHOPLY: jalankan seluruh file ini melalui Supabase SQL Editor.
create table if not exists public.customers (
  id bigint generated by default as identity primary key,
  full_name text not null,
  phone text,
  email text,
  address text,
  created_at timestamptz not null default now(),
  constraint customers_email_unique unique (email)
);

create table if not exists public.services (
  id bigint generated by default as identity primary key,
  name text not null unique,
  category text not null check (category in ('Jasa', 'Produk')),
  brand text,
  product_type text check (product_type in ('Sepatu', 'Tas', 'Pakaian', 'Aksesori', 'Lainnya')),
  image_url text,
  description text,
  price numeric(12, 2) not null default 0 check (price >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.services add column if not exists brand text;
alter table public.services add column if not exists product_type text;
alter table public.services add column if not exists image_url text;

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  customer_id bigint not null references public.customers(id) on update cascade on delete restrict,
  transaction_date date not null default current_date,
  payment_status text not null default 'Belum dibayar'
    check (payment_status in ('Belum dibayar', 'Sebagian', 'Lunas')),
  service_fee numeric(12, 2) not null default 0 check (service_fee >= 0),
  amount_paid numeric(12, 2) not null default 0 check (amount_paid >= 0),
  notes text,
  details jsonb not null default '[]'::jsonb check (jsonb_typeof(details) = 'array'),
  created_at timestamptz not null default now()
);

alter table public.transactions add column if not exists details jsonb not null default '[]'::jsonb;

create table if not exists public.finance_records (
  id bigint generated by default as identity primary key,
  record_type text not null check (record_type in ('account', 'journal')),
  account_code text,
  account_name text,
  account_type text check (account_type in ('Aset', 'Liabilitas', 'Modal', 'Pendapatan', 'Beban')),
  entry_date date,
  reference text,
  description text,
  lines jsonb not null default '[]'::jsonb check (jsonb_typeof(lines) = 'array'),
  created_at timestamptz not null default now(),
  constraint finance_records_account_unique unique (record_type, account_code),
  constraint finance_records_reference_unique unique (reference),
  constraint finance_records_shape check (
    (record_type = 'account' and account_code is not null and account_name is not null and account_type is not null and reference is null)
    or (record_type = 'journal' and entry_date is not null and reference is not null and description is not null)
  )
);

-- Copy legacy rows before removing the old tables, so rerunning this script keeps existing data.
do $$
begin
  if to_regclass('public.transaction_details') is not null then
    update public.transactions t
    set details = coalesce((
      select jsonb_agg(jsonb_build_object(
        'id', d.id,
        'service_id', d.service_id,
        'quantity', d.quantity,
        'unit_price', d.unit_price,
        'subtotal', d.subtotal
      ) order by d.id)
      from public.transaction_details d
      where d.transaction_id = t.id
    ), '[]'::jsonb)
    where t.details = '[]'::jsonb;
  end if;

  if to_regclass('public.accounts') is not null then
    insert into public.finance_records (record_type, account_code, account_name, account_type)
    select 'account', code, name, account_type from public.accounts
    on conflict (record_type, account_code) do nothing;
  end if;

  if to_regclass('public.journal_entries') is not null and to_regclass('public.journal_lines') is not null then
    insert into public.finance_records (record_type, entry_date, reference, description, lines)
    select 'journal', e.entry_date, e.reference, e.description, coalesce(
      jsonb_agg(jsonb_build_object(
        'account_code', a.code,
        'account_name', a.name,
        'account_type', a.account_type,
        'description', l.description,
        'debit', l.debit,
        'credit', l.credit
      ) order by l.id) filter (where l.id is not null), '[]'::jsonb
    )
    from public.journal_entries e
    left join public.journal_lines l on l.journal_entry_id = e.id
    left join public.accounts a on a.id = l.account_id
    group by e.id
    on conflict (reference) do nothing;
  end if;
end $$;

drop table if exists public.journal_lines;
drop table if exists public.journal_entries;
drop table if exists public.accounts;
drop table if exists public.transaction_details;

-- Untuk tugas/demo: akses anon diizinkan melalui API Supabase.
alter table public.customers disable row level security;
alter table public.services disable row level security;
alter table public.transactions disable row level security;
alter table public.finance_records disable row level security;

grant select, insert, update, delete on public.customers to anon, authenticated;
grant select, insert, update, delete on public.services to anon, authenticated;
grant select, insert, update, delete on public.transactions to anon, authenticated;
grant select, insert, update, delete on public.finance_records to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('shoply-products', 'shoply-products', true, 5242880, array['image/jpeg', 'image/png', 'image/webp'])
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'SHOPLY product photos are public'
  ) then
    create policy "SHOPLY product photos are public" on storage.objects
      for select to public using (bucket_id = 'shoply-products');
  end if;
  if not exists (
    select 1 from pg_policies
    where schemaname = 'storage' and tablename = 'objects' and policyname = 'SHOPLY can upload product photos'
  ) then
    create policy "SHOPLY can upload product photos" on storage.objects
      for insert to anon, authenticated with check (bucket_id = 'shoply-products');
  end if;
end $$;

insert into public.finance_records (record_type, account_code, account_name, account_type)
values
  ('account', '1001', 'Kas', 'Aset'),
  ('account', '1101', 'Piutang Usaha', 'Aset'),
  ('account', '2101', 'Utang Usaha', 'Liabilitas'),
  ('account', '2201', 'Uang Muka Pelanggan', 'Liabilitas'),
  ('account', '3001', 'Modal Pemilik', 'Modal'),
  ('account', '4001', 'Pendapatan Jasa', 'Pendapatan'),
  ('account', '4101', 'Penjualan Produk', 'Pendapatan'),
  ('account', '5001', 'Beban Pokok Produk', 'Beban'),
  ('account', '5101', 'Beban Operasional', 'Beban')
on conflict (record_type, account_code) do nothing;

insert into public.customers (full_name, phone, email, address)
values
  ('Alya Putri', '081234567890', 'alya@example.com', 'Jakarta'),
  ('Nadia Rahma', '082198765432', 'nadia@example.com', 'Bandung')
on conflict (email) do nothing;

insert into public.services (name, category, description, price)
values
  ('Jasa Personal Shopper', 'Jasa', 'Pendampingan dan pencarian fashion sesuai kebutuhan.', 150000),
  ('Kemeja Linen', 'Produk', 'Kemeja linen pilihan dari butik lokal.', 350000),
  ('Tas Selempang', 'Produk', 'Tas selempang pilihan.', 425000)
on conflict do nothing;

-- Referensi katalog demo: foto ilustrasi dan harga estimasi, bukan penawaran atau stok resmi.
insert into public.services (name, category, brand, product_type, image_url, description, price)
values
  ('Ace GG Canvas Sneaker', 'Produk', 'GUCCI', 'Sepatu', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85', 'Referensi gaya Gucci Ace. Foto ilustrasi; verifikasi model, harga, dan ketersediaan di butik.', 12500000),
  ('Gucci Giglio Small Tote Bag', 'Produk', 'GUCCI', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Model Giglio small tote, variasi sand/brown GG. Foto katalog Gucci US; harga di SHOPLY tetap estimasi lokal.', 29600000),
  ('Horsebit 1955 Mini Bag', 'Produk', 'GUCCI', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi gaya Horsebit. Foto ilustrasi; verifikasi model, harga, dan ketersediaan di butik.', 36000000),
  ('Interlocking G Leather Belt', 'Produk', 'GUCCI', 'Aksesori', 'https://images.unsplash.com/photo-1624222247344-550fb8d865a2?auto=format&fit=crop&w=900&q=85', 'Referensi aksesori Gucci. Foto ilustrasi; verifikasi model, harga, dan ketersediaan di butik.', 7200000),

  ('Vienna Leather Tote Bag', 'Produk', 'PEDRO', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi koleksi Vienna PEDRO. Foto ilustrasi; harga estimasi, cek harga dan stok terbaru di butik.', 2750000),
  ('Mirelle Leather Shoulder Bag', 'Produk', 'PEDRO', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi koleksi Mirelle PEDRO. Foto ilustrasi; harga estimasi, cek harga dan stok terbaru di butik.', 1800000),
  ('Jatte Crescent Bag', 'Produk', 'PEDRO', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi koleksi Jatte PEDRO. Foto ilustrasi; harga estimasi, cek harga dan stok terbaru di butik.', 1100000),
  ('Vienna Suede Tote Bag', 'Produk', 'PEDRO', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi koleksi Vienna suede PEDRO. Foto ilustrasi; harga estimasi, cek harga dan stok terbaru di butik.', 2750000),

  ('Leather Comfort Walking Sneaker', 'Produk', 'HUSH PUPPIES', 'Sepatu', 'https://images.unsplash.com/photo-1495555961986-6d4c1ecb7be3?auto=format&fit=crop&w=900&q=85', 'Pilihan sepatu comfort Hush Puppies. Foto ilustrasi; konfirmasi model dan stok resmi.', 1850000),
  ('Soft Leather Penny Loafer', 'Produk', 'HUSH PUPPIES', 'Sepatu', 'https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=900&q=85', 'Pilihan loafer kulit Hush Puppies. Foto ilustrasi; konfirmasi model dan stok resmi.', 1650000),
  ('Everyday Leather Crossbody', 'Produk', 'HUSH PUPPIES', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Pilihan tas sehari-hari Hush Puppies. Foto ilustrasi; konfirmasi model dan stok resmi.', 1450000),
  ('Relaxed Cotton Shirt', 'Produk', 'HUSH PUPPIES', 'Pakaian', 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?auto=format&fit=crop&w=900&q=85', 'Pilihan pakaian kasual Hush Puppies. Foto ilustrasi; konfirmasi model dan stok resmi.', 950000),

  ('Women L.12.D Stretch Mini Pique Polo', 'Produk', 'LACOSTE', 'Pakaian', 'https://images.unsplash.com/photo-1576566588028-4147f3842f27?auto=format&fit=crop&w=900&q=85', 'Nama merujuk pada lini polo wanita Lacoste; foto ilustrasi dan harga estimasi.', 2300000),
  ('Regular Fit Supple Petit Pique Polo', 'Produk', 'LACOSTE', 'Pakaian', 'https://images.unsplash.com/photo-1625910513413-5fc45e6f3f9c?auto=format&fit=crop&w=900&q=85', 'Referensi polo petit pique Lacoste; foto ilustrasi dan harga estimasi.', 1850000),
  ('L.12.12 Concept Tote Bag', 'Produk', 'LACOSTE', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi tote Lacoste; foto ilustrasi dan harga estimasi.', 2100000),
  ('Carnaby Pro Leather Sneaker', 'Produk', 'LACOSTE', 'Sepatu', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85', 'Referensi sneaker Lacoste; foto ilustrasi dan harga estimasi.', 2500000),

  ('Speedy Bandouliere 25', 'Produk', 'LOUIS VUITTON', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi lini Speedy Louis Vuitton. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 38500000),
  ('Neverfull MM Tote', 'Produk', 'LOUIS VUITTON', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi lini Neverfull Louis Vuitton. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 42500000),
  ('LV Trainer Sneaker', 'Produk', 'LOUIS VUITTON', 'Sepatu', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85', 'Referensi sneaker Louis Vuitton. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 26500000),
  ('LV Initiales 30mm Reversible Belt', 'Produk', 'LOUIS VUITTON', 'Aksesori', 'https://images.unsplash.com/photo-1624222247344-550fb8d865a2?auto=format&fit=crop&w=900&q=85', 'Referensi aksesori Louis Vuitton. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 11200000),

  ('Re-Nylon Backpack', 'Produk', 'PRADA', 'Tas', 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=900&q=85', 'Referensi lini Re-Nylon Prada. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 31500000),
  ('Galleria Saffiano Mini Bag', 'Produk', 'PRADA', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi lini Galleria Prada. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 52000000),
  ('Monolith Leather Loafer', 'Produk', 'PRADA', 'Sepatu', 'https://images.unsplash.com/photo-1531310197839-ccf54634509e?auto=format&fit=crop&w=900&q=85', 'Referensi loafer Prada. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 23500000),
  ('Saffiano Card Holder', 'Produk', 'PRADA', 'Aksesori', 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&w=900&q=85', 'Referensi aksesori Saffiano Prada. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 7800000),

  ('Classic 11.12 Handbag', 'Produk', 'CHANEL', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi lini Classic Chanel. Foto ilustrasi; harga dan ketersediaan perlu dikonfirmasi ke butik.', 185000000),
  ('Chanel 22 Mini Handbag', 'Produk', 'CHANEL', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi lini Chanel 22. Foto ilustrasi; harga dan ketersediaan perlu dikonfirmasi ke butik.', 98000000),
  ('Two-Tone Slingback Shoes', 'Produk', 'CHANEL', 'Sepatu', 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', 'Referensi slingback Chanel. Foto ilustrasi; harga dan ketersediaan perlu dikonfirmasi ke butik.', 24500000),
  ('CC Pearl Drop Earrings', 'Produk', 'CHANEL', 'Aksesori', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=85', 'Referensi perhiasan Chanel. Foto ilustrasi; harga dan ketersediaan perlu dikonfirmasi ke butik.', 11500000),

  ('Lady Dior Medium Bag', 'Produk', 'DIOR', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi lini Lady Dior. Foto ilustrasi; verifikasi model, harga, dan ketersediaan di butik.', 112000000),
  ('Dior Book Tote Small', 'Produk', 'DIOR', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi lini Book Tote. Foto ilustrasi; verifikasi model, harga, dan ketersediaan di butik.', 68000000),
  ('JAdior Slingback Pump', 'Produk', 'DIOR', 'Sepatu', 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', 'Referensi slingback Dior. Foto ilustrasi; verifikasi model, harga, dan ketersediaan di butik.', 23500000),
  ('Dior Tribales Earrings', 'Produk', 'DIOR', 'Aksesori', 'https://images.unsplash.com/photo-1611652022419-a9419f74343d?auto=format&fit=crop&w=900&q=85', 'Referensi perhiasan Dior. Foto ilustrasi; verifikasi model, harga, dan ketersediaan di butik.', 9600000),

  ('Birkin 25 Handbag', 'Produk', 'HERMÈS', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi lini Birkin Hermès. Foto ilustrasi; harga, antrean, dan ketersediaan wajib dikonfirmasi ke butik.', 285000000),
  ('Picotin Lock 18 Bag', 'Produk', 'HERMÈS', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi lini Picotin Hermès. Foto ilustrasi; harga dan ketersediaan perlu dikonfirmasi ke butik.', 68000000),
  ('Oran Sandal', 'Produk', 'HERMÈS', 'Sepatu', 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', 'Referensi sandal Oran Hermès. Foto ilustrasi; harga dan ketersediaan perlu dikonfirmasi ke butik.', 11800000),
  ('Twilly dHermes Silk Scarf', 'Produk', 'HERMÈS', 'Aksesori', 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=900&q=85', 'Referensi aksesori sutra Hermès. Foto ilustrasi; harga dan ketersediaan perlu dikonfirmasi ke butik.', 4800000),

  ('Baguette Chain Medium Bag', 'Produk', 'FENDI', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi lini Baguette Fendi. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 65500000),
  ('Peekaboo ISeeU Petite', 'Produk', 'FENDI', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi lini Peekaboo Fendi. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 82500000),
  ('Fendi First Leather Slingback', 'Produk', 'FENDI', 'Sepatu', 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', 'Referensi sepatu Fendi. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 22500000),
  ('FF Logo Leather Belt', 'Produk', 'FENDI', 'Aksesori', 'https://images.unsplash.com/photo-1624222247344-550fb8d865a2?auto=format&fit=crop&w=900&q=85', 'Referensi aksesori Fendi. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 9800000),

  ('Kensington Heritage Trench Coat', 'Produk', 'BURBERRY', 'Pakaian', 'https://images.unsplash.com/photo-1548126032-079a0fb0099d?auto=format&fit=crop&w=900&q=85', 'Referensi trench coat Burberry. Foto ilustrasi; konfirmasi harga dan ketersediaan di butik.', 46500000),
  ('Check Cashmere Scarf', 'Produk', 'BURBERRY', 'Aksesori', 'https://images.unsplash.com/photo-1606760227091-3dd870d97f1d?auto=format&fit=crop&w=900&q=85', 'Referensi scarf Burberry. Foto ilustrasi; konfirmasi harga dan ketersediaan di butik.', 9200000),
  ('Lola Quilted Shoulder Bag', 'Produk', 'BURBERRY', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi lini Lola Burberry. Foto ilustrasi; konfirmasi harga dan ketersediaan di butik.', 32500000),
  ('Leather Low-Top Sneaker', 'Produk', 'BURBERRY', 'Sepatu', 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?auto=format&fit=crop&w=900&q=85', 'Referensi sneaker Burberry. Foto ilustrasi; konfirmasi harga dan ketersediaan di butik.', 11200000),

  ('Rockstud Slingback Pump', 'Produk', 'VALENTINO', 'Sepatu', 'https://images.unsplash.com/photo-1543163521-1bf539c55dd2?auto=format&fit=crop&w=900&q=85', 'Referensi lini Rockstud Valentino Garavani. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 24500000),
  ('VLogo Signature Shoulder Bag', 'Produk', 'VALENTINO', 'Tas', 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=900&q=85', 'Referensi lini VLogo Valentino Garavani. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 42500000),
  ('Roman Stud Small Shoulder Bag', 'Produk', 'VALENTINO', 'Tas', 'https://images.unsplash.com/photo-1590874103328-eac38a683ce7?auto=format&fit=crop&w=900&q=85', 'Referensi lini Roman Stud Valentino Garavani. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 58500000),
  ('VLogo Signature Leather Belt', 'Produk', 'VALENTINO', 'Aksesori', 'https://images.unsplash.com/photo-1624222247344-550fb8d865a2?auto=format&fit=crop&w=900&q=85', 'Referensi aksesori Valentino Garavani. Foto ilustrasi; verifikasi harga dan ketersediaan di butik.', 10500000)
on conflict (name) do nothing;

-- Jangan tampilkan foto stok generik seolah-olah merupakan foto barang bermerek.
update public.services
set image_url = null
where brand is not null and image_url like 'https://images.unsplash.com/%';

-- Foto produk exact dari halaman katalog brand; harga tetap perlu dikonfirmasi ke butik.
update public.services
set image_url = 'https://media.gucci.com/style/DarkGray_Center_0_0_980x980/1765905326/860845_FAF3Y_2155_001_074_0045_Light-gucci-giglio-small-tote-bag.jpg'
where name = 'Gucci Giglio Small Tote Bag' and brand = 'GUCCI'
  and (image_url is null or image_url like 'https://images.unsplash.com/%');

update public.services
set image_url = 'https://www.pedroshoes.com/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-pd-products/default/dwad41d07a/images/hi-res/2026-L7-PW2-45060030-29-1.jpg?sw=900&sh=1200'
where name = 'Vienna Leather Tote Bag' and brand = 'PEDRO'
  and (image_url is null or image_url like 'https://images.unsplash.com/%');

update public.services
set image_url = 'https://www.pedroshoes.com/dw/image/v2/BCWJ_PRD/on/demandware.static/-/Sites-pd-products/default/dwb2b72922/images/hi-res/2025-L6-PW2-75210182-41-1.jpg?sw=900&sh=1200'
where name = 'Jatte Crescent Bag' and brand = 'PEDRO'
  and (image_url is null or image_url like 'https://images.unsplash.com/%');

update public.services
set image_url = 'https://imagena1.lacoste.com/dw/image/v2/AAUP_PRD/on/demandware.static/-/Sites-master/default/dwebad0959/PF7839_001_20.jpg?imwidth=760&impolicy=pctp'
where name = 'Regular Fit Supple Petit Pique Polo' and brand = 'LACOSTE'
  and (image_url is null or image_url like 'https://images.unsplash.com/%');

insert into public.transactions (customer_id, transaction_date, payment_status, service_fee, amount_paid, notes)
select id, current_date, 'Lunas', 150000, 500000, 'Contoh transaksi lunas'
from public.customers
where email = 'alya@example.com'
  and not exists (
    select 1 from public.transactions t
    where t.customer_id = public.customers.id and t.notes = 'Contoh transaksi lunas'
  );

update public.transactions t
set details = jsonb_build_array(jsonb_build_object(
  'id', -1,
  'service_id', s.id,
  'quantity', 1,
  'unit_price', s.price,
  'subtotal', s.price
))
from public.customers c, public.services s
where t.customer_id = c.id
  and c.email = 'alya@example.com'
  and t.notes = 'Contoh transaksi lunas'
  and s.name = 'Kemeja Linen'
  and t.details = '[]'::jsonb;